---

- include: debian-install.yml
  when: ansible_os_family == "Debian"
  tags: install

- include: debian-config.yml
  when: ansible_os_family == "Debian"
  tags: config

- include: redhat-install.yml
  when: ansible_os_family == 'RedHat'
  tags: install

- include: redhat-config.yml
  when: ansible_os_family == 'RedHat'
  tags: config
